### ISSUE TITLE
Large data affects few pages stop rendering 

### ISSUE THREAD

**Issue by vanillacandy** [pacphi/cf-hoover-ui#49]
Cf-hoover-ui stop showing snapshot-detail-services, snapshot-detail-application, or snapshot-detail-users when the data in those pages reach certain large limit.

**Comment by pacphi** [comment]
Need to have a look at https://vaadin.com/docs/flow/binding-data/tutorial-flow-data-provider.html and see about swapping out ListDataProvider which is an in-memory provider to some kind of query/fetch, lazy-load, from cache.

**Comment by pacphi** [comment]
Upstream in `cf-hoover` if the dataset is large enough it can cause the direct memory buffer to be exhausted. I've tuned this upstream in https://github.com/pacphi/cf-hoover/commit/1ee97d2968b6966ce06255d292afbfabfa7de896.
